//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWeb.Cliente_GuardarCatalogoTxt {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Cliente_GuardarCatalogoTxt.IGuardarCatalogoTxt")]
    public interface IGuardarCatalogoTxt {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuardarCatalogoTxt/guardarCatalogoTxt", ReplyAction="http://tempuri.org/IGuardarCatalogoTxt/guardarCatalogoTxtResponse")]
        string guardarCatalogoTxt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuardarCatalogoTxt/guardarCatalogoTxt", ReplyAction="http://tempuri.org/IGuardarCatalogoTxt/guardarCatalogoTxtResponse")]
        System.Threading.Tasks.Task<string> guardarCatalogoTxtAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGuardarCatalogoTxtChannel : AppWeb.Cliente_GuardarCatalogoTxt.IGuardarCatalogoTxt, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GuardarCatalogoTxtClient : System.ServiceModel.ClientBase<AppWeb.Cliente_GuardarCatalogoTxt.IGuardarCatalogoTxt>, AppWeb.Cliente_GuardarCatalogoTxt.IGuardarCatalogoTxt {
        
        public GuardarCatalogoTxtClient() {
        }
        
        public GuardarCatalogoTxtClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GuardarCatalogoTxtClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuardarCatalogoTxtClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuardarCatalogoTxtClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string guardarCatalogoTxt() {
            return base.Channel.guardarCatalogoTxt();
        }
        
        public System.Threading.Tasks.Task<string> guardarCatalogoTxtAsync() {
            return base.Channel.guardarCatalogoTxtAsync();
        }
    }
}
