//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWeb.ServiceReference7 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference7.IServicioModificarParametros")]
    public interface IServicioModificarParametros {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioModificarParametros/ModificarArancel", ReplyAction="http://tempuri.org/IServicioModificarParametros/ModificarArancelResponse")]
        bool ModificarArancel(double value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioModificarParametros/ModificarArancel", ReplyAction="http://tempuri.org/IServicioModificarParametros/ModificarArancelResponse")]
        System.Threading.Tasks.Task<bool> ModificarArancelAsync(double value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioModificarParametros/ModificarPorcentajeExtra", ReplyAction="http://tempuri.org/IServicioModificarParametros/ModificarPorcentajeExtraResponse")]
        bool ModificarPorcentajeExtra(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioModificarParametros/ModificarPorcentajeExtra", ReplyAction="http://tempuri.org/IServicioModificarParametros/ModificarPorcentajeExtraResponse")]
        System.Threading.Tasks.Task<bool> ModificarPorcentajeExtraAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioModificarParametros/ObtenerArancel", ReplyAction="http://tempuri.org/IServicioModificarParametros/ObtenerArancelResponse")]
        double ObtenerArancel();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioModificarParametros/ObtenerArancel", ReplyAction="http://tempuri.org/IServicioModificarParametros/ObtenerArancelResponse")]
        System.Threading.Tasks.Task<double> ObtenerArancelAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioModificarParametros/ObtenerPorcentajeExtra", ReplyAction="http://tempuri.org/IServicioModificarParametros/ObtenerPorcentajeExtraResponse")]
        int ObtenerPorcentajeExtra();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioModificarParametros/ObtenerPorcentajeExtra", ReplyAction="http://tempuri.org/IServicioModificarParametros/ObtenerPorcentajeExtraResponse")]
        System.Threading.Tasks.Task<int> ObtenerPorcentajeExtraAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioModificarParametrosChannel : AppWeb.ServiceReference7.IServicioModificarParametros, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioModificarParametrosClient : System.ServiceModel.ClientBase<AppWeb.ServiceReference7.IServicioModificarParametros>, AppWeb.ServiceReference7.IServicioModificarParametros {
        
        public ServicioModificarParametrosClient() {
        }
        
        public ServicioModificarParametrosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioModificarParametrosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioModificarParametrosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioModificarParametrosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ModificarArancel(double value) {
            return base.Channel.ModificarArancel(value);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarArancelAsync(double value) {
            return base.Channel.ModificarArancelAsync(value);
        }
        
        public bool ModificarPorcentajeExtra(int value) {
            return base.Channel.ModificarPorcentajeExtra(value);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarPorcentajeExtraAsync(int value) {
            return base.Channel.ModificarPorcentajeExtraAsync(value);
        }
        
        public double ObtenerArancel() {
            return base.Channel.ObtenerArancel();
        }
        
        public System.Threading.Tasks.Task<double> ObtenerArancelAsync() {
            return base.Channel.ObtenerArancelAsync();
        }
        
        public int ObtenerPorcentajeExtra() {
            return base.Channel.ObtenerPorcentajeExtra();
        }
        
        public System.Threading.Tasks.Task<int> ObtenerPorcentajeExtraAsync() {
            return base.Channel.ObtenerPorcentajeExtraAsync();
        }
    }
}
