//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWeb.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IProveedorDadoRUT")]
    public interface IProveedorDadoRUT {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedorDadoRUT/buscarProveedorRut", ReplyAction="http://tempuri.org/IProveedorDadoRUT/buscarProveedorRutResponse")]
        WCFProveedorDadoRUT.DtoProveedor buscarProveedorRut(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedorDadoRUT/buscarProveedorRut", ReplyAction="http://tempuri.org/IProveedorDadoRUT/buscarProveedorRutResponse")]
        System.Threading.Tasks.Task<WCFProveedorDadoRUT.DtoProveedor> buscarProveedorRutAsync(string rut);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProveedorDadoRUTChannel : AppWeb.ServiceReference1.IProveedorDadoRUT, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProveedorDadoRUTClient : System.ServiceModel.ClientBase<AppWeb.ServiceReference1.IProveedorDadoRUT>, AppWeb.ServiceReference1.IProveedorDadoRUT {
        
        public ProveedorDadoRUTClient() {
        }
        
        public ProveedorDadoRUTClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProveedorDadoRUTClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProveedorDadoRUTClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProveedorDadoRUTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFProveedorDadoRUT.DtoProveedor buscarProveedorRut(string rut) {
            return base.Channel.buscarProveedorRut(rut);
        }
        
        public System.Threading.Tasks.Task<WCFProveedorDadoRUT.DtoProveedor> buscarProveedorRutAsync(string rut) {
            return base.Channel.buscarProveedorRutAsync(rut);
        }
    }
}
