//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWeb.Cliente_DesactivarProv {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Cliente_DesactivarProv.IDesactivarProv")]
    public interface IDesactivarProv {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesactivarProv/desactivarProvRut", ReplyAction="http://tempuri.org/IDesactivarProv/desactivarProvRutResponse")]
        string desactivarProvRut(string Rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDesactivarProv/desactivarProvRut", ReplyAction="http://tempuri.org/IDesactivarProv/desactivarProvRutResponse")]
        System.Threading.Tasks.Task<string> desactivarProvRutAsync(string Rut);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDesactivarProvChannel : AppWeb.Cliente_DesactivarProv.IDesactivarProv, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DesactivarProvClient : System.ServiceModel.ClientBase<AppWeb.Cliente_DesactivarProv.IDesactivarProv>, AppWeb.Cliente_DesactivarProv.IDesactivarProv {
        
        public DesactivarProvClient() {
        }
        
        public DesactivarProvClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DesactivarProvClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DesactivarProvClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DesactivarProvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string desactivarProvRut(string Rut) {
            return base.Channel.desactivarProvRut(Rut);
        }
        
        public System.Threading.Tasks.Task<string> desactivarProvRutAsync(string Rut) {
            return base.Channel.desactivarProvRutAsync(Rut);
        }
    }
}
