//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWeb.Cliente_GuardarProvTxt {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Cliente_GuardarProvTxt.IGuardarProvTxt")]
    public interface IGuardarProvTxt {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuardarProvTxt/guardarProveedoresTxt", ReplyAction="http://tempuri.org/IGuardarProvTxt/guardarProveedoresTxtResponse")]
        string guardarProveedoresTxt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuardarProvTxt/guardarProveedoresTxt", ReplyAction="http://tempuri.org/IGuardarProvTxt/guardarProveedoresTxtResponse")]
        System.Threading.Tasks.Task<string> guardarProveedoresTxtAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGuardarProvTxtChannel : AppWeb.Cliente_GuardarProvTxt.IGuardarProvTxt, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GuardarProvTxtClient : System.ServiceModel.ClientBase<AppWeb.Cliente_GuardarProvTxt.IGuardarProvTxt>, AppWeb.Cliente_GuardarProvTxt.IGuardarProvTxt {
        
        public GuardarProvTxtClient() {
        }
        
        public GuardarProvTxtClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GuardarProvTxtClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuardarProvTxtClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GuardarProvTxtClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string guardarProveedoresTxt() {
            return base.Channel.guardarProveedoresTxt();
        }
        
        public System.Threading.Tasks.Task<string> guardarProveedoresTxtAsync() {
            return base.Channel.guardarProveedoresTxtAsync();
        }
    }
}
