//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWeb.ServiceReference9 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoUsuario", Namespace="http://schemas.datacontract.org/2004/07/WcfAgregarProv")]
    [System.SerializableAttribute()]
    public partial class DtoUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Passw {
            get {
                return this.PasswField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswField, value) != true)) {
                    this.PasswField = value;
                    this.RaisePropertyChanged("Passw");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rol {
            get {
                return this.RolField;
            }
            set {
                if ((this.RolField.Equals(value) != true)) {
                    this.RolField = value;
                    this.RaisePropertyChanged("Rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoProveedor", Namespace="http://schemas.datacontract.org/2004/07/WcfAgregarProv")]
    [System.SerializableAttribute()]
    public partial class DtoProveedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppWeb.ServiceReference9.DtoServicioProveedor[] ListaServiciosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Dominio.Usuario MiUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreFantasiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool esInactivoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaRegistroField, value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppWeb.ServiceReference9.DtoServicioProveedor[] ListaServicios {
            get {
                return this.ListaServiciosField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaServiciosField, value) != true)) {
                    this.ListaServiciosField = value;
                    this.RaisePropertyChanged("ListaServicios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Dominio.Usuario MiUsuario {
            get {
                return this.MiUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.MiUsuarioField, value) != true)) {
                    this.MiUsuarioField = value;
                    this.RaisePropertyChanged("MiUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreFantasia {
            get {
                return this.NombreFantasiaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreFantasiaField, value) != true)) {
                    this.NombreFantasiaField = value;
                    this.RaisePropertyChanged("NombreFantasia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUT {
            get {
                return this.RUTField;
            }
            set {
                if ((object.ReferenceEquals(this.RUTField, value) != true)) {
                    this.RUTField = value;
                    this.RaisePropertyChanged("RUT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool esInactivo {
            get {
                return this.esInactivoField;
            }
            set {
                if ((this.esInactivoField.Equals(value) != true)) {
                    this.esInactivoField = value;
                    this.RaisePropertyChanged("esInactivo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoServicioProveedor", Namespace="http://schemas.datacontract.org/2004/07/WcfAgregarProv")]
    [System.SerializableAttribute()]
    public partial class DtoServicioProveedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutProveedorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdServicio {
            get {
                return this.IdServicioField;
            }
            set {
                if ((this.IdServicioField.Equals(value) != true)) {
                    this.IdServicioField = value;
                    this.RaisePropertyChanged("IdServicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutProveedor {
            get {
                return this.RutProveedorField;
            }
            set {
                if ((object.ReferenceEquals(this.RutProveedorField, value) != true)) {
                    this.RutProveedorField = value;
                    this.RaisePropertyChanged("RutProveedor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoServicio", Namespace="http://schemas.datacontract.org/2004/07/WcfAgregarProv")]
    [System.SerializableAttribute()]
    public partial class DtoServicio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppWeb.ServiceReference9.DtoTipoEvento[] ListaTipoEventosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdServicio {
            get {
                return this.IdServicioField;
            }
            set {
                if ((this.IdServicioField.Equals(value) != true)) {
                    this.IdServicioField = value;
                    this.RaisePropertyChanged("IdServicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppWeb.ServiceReference9.DtoTipoEvento[] ListaTipoEventos {
            get {
                return this.ListaTipoEventosField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaTipoEventosField, value) != true)) {
                    this.ListaTipoEventosField = value;
                    this.RaisePropertyChanged("ListaTipoEventos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoTipoEvento", Namespace="http://schemas.datacontract.org/2004/07/WcfAgregarProv")]
    [System.SerializableAttribute()]
    public partial class DtoTipoEvento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idTipoEventoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTipoEvento {
            get {
                return this.idTipoEventoField;
            }
            set {
                if ((this.idTipoEventoField.Equals(value) != true)) {
                    this.idTipoEventoField = value;
                    this.RaisePropertyChanged("idTipoEvento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference9.IAgregarProv")]
    public interface IAgregarProv {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgregarProv/InsertarProveedor", ReplyAction="http://tempuri.org/IAgregarProv/InsertarProveedorResponse")]
        bool InsertarProveedor(string rut, string nombreFantasia, string email, string tel, bool esInactivo, bool esVip, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgregarProv/InsertarProveedor", ReplyAction="http://tempuri.org/IAgregarProv/InsertarProveedorResponse")]
        System.Threading.Tasks.Task<bool> InsertarProveedorAsync(string rut, string nombreFantasia, string email, string tel, bool esInactivo, bool esVip, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgregarProv/AgregarUsuario", ReplyAction="http://tempuri.org/IAgregarProv/AgregarUsuarioResponse")]
        bool AgregarUsuario(AppWeb.ServiceReference9.DtoUsuario usu, AppWeb.ServiceReference9.DtoProveedor prov);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgregarProv/AgregarUsuario", ReplyAction="http://tempuri.org/IAgregarProv/AgregarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> AgregarUsuarioAsync(AppWeb.ServiceReference9.DtoUsuario usu, AppWeb.ServiceReference9.DtoProveedor prov);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgregarProv/AgregarServicioAProveedor", ReplyAction="http://tempuri.org/IAgregarProv/AgregarServicioAProveedorResponse")]
        bool AgregarServicioAProveedor(AppWeb.ServiceReference9.DtoServicioProveedor servicio, AppWeb.ServiceReference9.DtoProveedor prov);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgregarProv/AgregarServicioAProveedor", ReplyAction="http://tempuri.org/IAgregarProv/AgregarServicioAProveedorResponse")]
        System.Threading.Tasks.Task<bool> AgregarServicioAProveedorAsync(AppWeb.ServiceReference9.DtoServicioProveedor servicio, AppWeb.ServiceReference9.DtoProveedor prov);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgregarProv/ExisteRUT", ReplyAction="http://tempuri.org/IAgregarProv/ExisteRUTResponse")]
        bool ExisteRUT(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgregarProv/ExisteRUT", ReplyAction="http://tempuri.org/IAgregarProv/ExisteRUTResponse")]
        System.Threading.Tasks.Task<bool> ExisteRUTAsync(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgregarProv/ExisteMail", ReplyAction="http://tempuri.org/IAgregarProv/ExisteMailResponse")]
        bool ExisteMail(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgregarProv/ExisteMail", ReplyAction="http://tempuri.org/IAgregarProv/ExisteMailResponse")]
        System.Threading.Tasks.Task<bool> ExisteMailAsync(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgregarProv/CargarServicios", ReplyAction="http://tempuri.org/IAgregarProv/CargarServiciosResponse")]
        AppWeb.ServiceReference9.DtoServicio[] CargarServicios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgregarProv/CargarServicios", ReplyAction="http://tempuri.org/IAgregarProv/CargarServiciosResponse")]
        System.Threading.Tasks.Task<AppWeb.ServiceReference9.DtoServicio[]> CargarServiciosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAgregarProvChannel : AppWeb.ServiceReference9.IAgregarProv, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgregarProvClient : System.ServiceModel.ClientBase<AppWeb.ServiceReference9.IAgregarProv>, AppWeb.ServiceReference9.IAgregarProv {
        
        public AgregarProvClient() {
        }
        
        public AgregarProvClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgregarProvClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgregarProvClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgregarProvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertarProveedor(string rut, string nombreFantasia, string email, string tel, bool esInactivo, bool esVip, string pass) {
            return base.Channel.InsertarProveedor(rut, nombreFantasia, email, tel, esInactivo, esVip, pass);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarProveedorAsync(string rut, string nombreFantasia, string email, string tel, bool esInactivo, bool esVip, string pass) {
            return base.Channel.InsertarProveedorAsync(rut, nombreFantasia, email, tel, esInactivo, esVip, pass);
        }
        
        public bool AgregarUsuario(AppWeb.ServiceReference9.DtoUsuario usu, AppWeb.ServiceReference9.DtoProveedor prov) {
            return base.Channel.AgregarUsuario(usu, prov);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarUsuarioAsync(AppWeb.ServiceReference9.DtoUsuario usu, AppWeb.ServiceReference9.DtoProveedor prov) {
            return base.Channel.AgregarUsuarioAsync(usu, prov);
        }
        
        public bool AgregarServicioAProveedor(AppWeb.ServiceReference9.DtoServicioProveedor servicio, AppWeb.ServiceReference9.DtoProveedor prov) {
            return base.Channel.AgregarServicioAProveedor(servicio, prov);
        }
        
        public System.Threading.Tasks.Task<bool> AgregarServicioAProveedorAsync(AppWeb.ServiceReference9.DtoServicioProveedor servicio, AppWeb.ServiceReference9.DtoProveedor prov) {
            return base.Channel.AgregarServicioAProveedorAsync(servicio, prov);
        }
        
        public bool ExisteRUT(string rut) {
            return base.Channel.ExisteRUT(rut);
        }
        
        public System.Threading.Tasks.Task<bool> ExisteRUTAsync(string rut) {
            return base.Channel.ExisteRUTAsync(rut);
        }
        
        public bool ExisteMail(string rut) {
            return base.Channel.ExisteMail(rut);
        }
        
        public System.Threading.Tasks.Task<bool> ExisteMailAsync(string rut) {
            return base.Channel.ExisteMailAsync(rut);
        }
        
        public AppWeb.ServiceReference9.DtoServicio[] CargarServicios() {
            return base.Channel.CargarServicios();
        }
        
        public System.Threading.Tasks.Task<AppWeb.ServiceReference9.DtoServicio[]> CargarServiciosAsync() {
            return base.Channel.CargarServiciosAsync();
        }
    }
}
