//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWeb.ServiceReference3 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoServicio", Namespace="http://schemas.datacontract.org/2004/07/WCFCatalogoServicios")]
    [System.SerializableAttribute()]
    public partial class DtoServicio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppWeb.ServiceReference3.DtoTipoEvento[] misTiposEventosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdServicio {
            get {
                return this.IdServicioField;
            }
            set {
                if ((this.IdServicioField.Equals(value) != true)) {
                    this.IdServicioField = value;
                    this.RaisePropertyChanged("IdServicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Servicio {
            get {
                return this.ServicioField;
            }
            set {
                if ((object.ReferenceEquals(this.ServicioField, value) != true)) {
                    this.ServicioField = value;
                    this.RaisePropertyChanged("Servicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppWeb.ServiceReference3.DtoTipoEvento[] misTiposEventos {
            get {
                return this.misTiposEventosField;
            }
            set {
                if ((object.ReferenceEquals(this.misTiposEventosField, value) != true)) {
                    this.misTiposEventosField = value;
                    this.RaisePropertyChanged("misTiposEventos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoTipoEvento", Namespace="http://schemas.datacontract.org/2004/07/WCFCatalogoServicios")]
    [System.SerializableAttribute()]
    public partial class DtoTipoEvento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.ICatalogoServicios")]
    public interface ICatalogoServicios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoServicios/ObtenerServicios", ReplyAction="http://tempuri.org/ICatalogoServicios/ObtenerServiciosResponse")]
        AppWeb.ServiceReference3.DtoServicio[] ObtenerServicios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoServicios/ObtenerServicios", ReplyAction="http://tempuri.org/ICatalogoServicios/ObtenerServiciosResponse")]
        System.Threading.Tasks.Task<AppWeb.ServiceReference3.DtoServicio[]> ObtenerServiciosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoServicios/BuscarServicio", ReplyAction="http://tempuri.org/ICatalogoServicios/BuscarServicioResponse")]
        AppWeb.ServiceReference3.DtoServicio BuscarServicio(int fila);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoServicios/BuscarServicio", ReplyAction="http://tempuri.org/ICatalogoServicios/BuscarServicioResponse")]
        System.Threading.Tasks.Task<AppWeb.ServiceReference3.DtoServicio> BuscarServicioAsync(int fila);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICatalogoServiciosChannel : AppWeb.ServiceReference3.ICatalogoServicios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatalogoServiciosClient : System.ServiceModel.ClientBase<AppWeb.ServiceReference3.ICatalogoServicios>, AppWeb.ServiceReference3.ICatalogoServicios {
        
        public CatalogoServiciosClient() {
        }
        
        public CatalogoServiciosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatalogoServiciosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogoServiciosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogoServiciosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AppWeb.ServiceReference3.DtoServicio[] ObtenerServicios() {
            return base.Channel.ObtenerServicios();
        }
        
        public System.Threading.Tasks.Task<AppWeb.ServiceReference3.DtoServicio[]> ObtenerServiciosAsync() {
            return base.Channel.ObtenerServiciosAsync();
        }
        
        public AppWeb.ServiceReference3.DtoServicio BuscarServicio(int fila) {
            return base.Channel.BuscarServicio(fila);
        }
        
        public System.Threading.Tasks.Task<AppWeb.ServiceReference3.DtoServicio> BuscarServicioAsync(int fila) {
            return base.Channel.BuscarServicioAsync(fila);
        }
    }
}
